# Generated by Django 3.1.6 on 2021-03-30 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('release_date', models.DateField(null=True)),
                ('actors', models.CharField(max_length=256)),
                ('genre', models.CharField(max_length=256)),
                ('trailer', models.URLField(max_length=128)),
                ('description', models.TextField(max_length=1024)),
                ('cover', models.ImageField(blank=True, upload_to='movie_images')),
                ('upload_date', models.DateField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_images')),
                ('description', models.TextField(default='', max_length=1024)),
                ('producer', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rotten_potatoes.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rotten_potatoes.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rotten_potatoes.userprofile'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1024)),
                ('time_posted', models.DateField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rotten_potatoes.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rotten_potatoes.userprofile')),
            ],
        ),
    ]
