# Generated by Django 2.2.17 on 2021-03-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotten_potatoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
    ]
