# Generated by Django 2.2.17 on 2021-04-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotten_potatoes', '0002_auto_20210402_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cover',
            field=models.ImageField(blank=True, default='movie_images/default.jpg', upload_to='movie_images'),
        ),
    ]
