# Generated by Django 2.2.17 on 2021-03-18 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rotten_potatoes', '0002_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('release_date', models.DateField(default='Unknown')),
                ('actors', models.CharField(max_length=256)),
                ('trailer', models.URLField(max_length=128)),
                ('description', models.TextField(max_length=1024)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rotten_potatoes.Genre')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rotten_potatoes.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rotten_potatoes.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rotten_potatoes.UserProfile')),
            ],
        ),
    ]
