# Generated by Django 2.2.17 on 2021-03-18 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rotten_potatoes', '0003_movie_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1024)),
                ('time_posted', models.DateField(default='Unknown')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rotten_potatoes.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rotten_potatoes.UserProfile')),
            ],
        ),
    ]
