# Generated by Django 2.2.17 on 2021-03-19 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotten_potatoes', '0004_auto_20210318_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cover',
            field=models.ImageField(blank=True, upload_to='movie_images'),
        ),
        migrations.AddField(
            model_name='movie',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 19, 11, 12, 36, 920557)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(max_length=256),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
