# Generated by Django 2.2.17 on 2021-03-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotten_potatoes', '0005_auto_20210319_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.TextField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='upload_date',
            field=models.DateField(),
        ),
    ]
