# Generated by Django 2.2.17 on 2021-03-22 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotten_potatoes', '0006_auto_20210319_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time_posted',
            field=models.DateField(default=datetime.datetime(2021, 3, 22, 13, 27, 2, 395180)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 22, 13, 27, 2, 394148)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 22, 13, 27, 2, 394148)),
        ),
    ]
