# Generated by Django 2.2.17 on 2021-03-22 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotten_potatoes', '0007_auto_20210322_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time_posted',
            field=models.DateField(default=datetime.datetime(2021, 3, 22, 13, 31, 50, 464137)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(default='Taken', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 22, 13, 31, 50, 463109)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 22, 13, 31, 50, 463109)),
        ),
    ]
